version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
    networks:
      - app

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./streamlit:/streamlit
    restart: always
    networks:
      - app

  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "8000:8000"
    volumes:
      - ./backend:/api
    restart: always
    networks:
      - app

  filebeat:
    image: elastic/filebeat:7.16.2
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./host_metrics_app/:/host_metrics_app/:ro
    networks:
      - app
    depends_on:
      - logstash  # Зависимость от Logstash, так как Filebeat будет отправлять логи именно туда

volumes:
  esdata:
    driver: local

networks:
  app:
    driver: bridge

